<?php

namespace Container2nLyCz6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EventsController' shared autowired service.
     *
     * @return \App\Controller\EventsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EventsController.php';

        $container->services['App\\Controller\\EventsController'] = $instance = new \App\Controller\EventsController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\EventsController', $container));

        return $instance;
    }
}
