<?php

namespace ContainerQhZfgkf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5ypzhUyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5ypzhUy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5ypzhUy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'postRepository' => ['privates', '.errored.Rrq8VBF', NULL, 'Cannot determine controller argument for "App\\Controller\\EventsController::index()": the $postRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\PostRepository". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'postRepository' => '?',
        ]);
    }
}
