<?php

namespace ContainerQhZfgkf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Rrq8VBFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Rrq8VBF' shared service.
     *
     * @return \App\Controller\PostRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\EventsController::index()": the $postRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\PostRepository". Did you forget to add a use statement?');
    }
}
