<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZe7ZDLN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZe7ZDLN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZe7ZDLN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZe7ZDLN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZe7ZDLN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ze7ZDLN',
    'container.build_id' => '0daedcf2',
    'container.build_time' => 1669751418,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZe7ZDLN');
