<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZDSBm6x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZDSBm6x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZDSBm6x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZDSBm6x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZDSBm6x\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZDSBm6x',
    'container.build_id' => 'ad4340fe',
    'container.build_time' => 1669791444,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZDSBm6x');
