<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKKCawMA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKKCawMA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKKCawMA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKKCawMA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKKCawMA\App_KernelDevDebugContainer([
    'container.build_hash' => 'KKCawMA',
    'container.build_id' => 'dbbc5957',
    'container.build_time' => 1669648598,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKKCawMA');
